# Generated by Django 4.2.7 on 2023-11-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digestapi', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
