# Generated by Django 4.2.7 on 2023-11-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digestapi', '0004_delete_user_rename_body_review_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='date',
            new_name='date_posted',
        ),
    ]
